// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmY4IaU7tUYjehuHSHEa_KgYwOZUFvAdA',
    appId: '1:343092674783:web:6a2c85f9d03ebb98db296a',
    messagingSenderId: '343092674783',
    projectId: 'ica13-d1f60',
    authDomain: 'ica13-d1f60.firebaseapp.com',
    storageBucket: 'ica13-d1f60.firebasestorage.app',
    measurementId: 'G-HN99ZCYTXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_E8wTAAtG4aTzNTNrMIp3KArjMBJZj9U',
    appId: '1:343092674783:android:3722df4dba3e3cf4db296a',
    messagingSenderId: '343092674783',
    projectId: 'ica13-d1f60',
    storageBucket: 'ica13-d1f60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHBoqbqBoqtOSLNRgZhTXWnneQzixp2UQ',
    appId: '1:343092674783:ios:d17322a522e4eec3db296a',
    messagingSenderId: '343092674783',
    projectId: 'ica13-d1f60',
    storageBucket: 'ica13-d1f60.firebasestorage.app',
    iosBundleId: 'com.example.ica13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHBoqbqBoqtOSLNRgZhTXWnneQzixp2UQ',
    appId: '1:343092674783:ios:d17322a522e4eec3db296a',
    messagingSenderId: '343092674783',
    projectId: 'ica13-d1f60',
    storageBucket: 'ica13-d1f60.firebasestorage.app',
    iosBundleId: 'com.example.ica13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmY4IaU7tUYjehuHSHEa_KgYwOZUFvAdA',
    appId: '1:343092674783:web:427a6a2a202a1f7cdb296a',
    messagingSenderId: '343092674783',
    projectId: 'ica13-d1f60',
    authDomain: 'ica13-d1f60.firebaseapp.com',
    storageBucket: 'ica13-d1f60.firebasestorage.app',
    measurementId: 'G-VF9DT0W3D4',
  );
}
